services:
  - type: web
    name: creativity-tikgrab
    runtime: python
    rootDir: tools/tool1
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
